name: Build and Push
on:
  push:
    paths:
      - 'ApiFlask/**'
      - 'k8s/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-push-APiFlask:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125784755:role/uc1-alb-oidc
          role-session-name: github-assume
          aws-region: us-east-1

      - name: Login to Amazon ECR # login ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image 
        run: |
          docker build -t ${{ vars.ECR_REGISTRY }}/flask-app:${{ github.sha }} ./Api-Flask
          docker tag ${{ vars.ECR_REGISTRY }}/flask-app:${{ github.sha }} ${{ vars.ECR_REGISTRY }}/flask-app:latest

      - name: Push Docker Image 
        run: |
          docker push ${{ vars.ECR_REGISTRY }}/flask-app:${{ github.sha }}
          docker push ${{ vars.ECR_REGISTRY }}/flask-app:latest
